export type PromoFields = {
  productName: string;
  oldPrice: number | null;
  newPrice: number;
  pixPrice: number | null;
  paymentTerms: string | null;
  couponCode: string | null;
  sizesAvailable: string | null;
  productLink: string;
  affiliateLink: string | null;
  introEmoji: string | null;
  introText: string | null;
  // Manual and Mercado Livre promos are always BRL; eBay's catalog is USD
  // (its search API has no BRL pricing) — formatting has to follow suit
  // instead of mislabeling a dollar amount with "R$".
  currency: string;
};

function fmtPrice(v: number, currency: string): string {
  const locale = currency === "BRL" ? "pt-BR" : "en-US";
  return v.toLocaleString(locale, { style: "currency", currency });
}

// WhatsApp only supports *bold*, _italic_, ~strikethrough~ and
// ```monospace``` — no color, no font size. Any colored pricing look in a
// reference screenshot is WhatsApp's own rendering, not something the
// sender controls; the preview (WhatsAppPromoPreview) applies decorative
// color only to spans whose bold/strike state came from parsing THIS
// generated string, never as an independent flourish. This function is the
// single source of truth for both the live preview and the "copiar texto"
// button — never two separate formatting code paths.
export function buildWhatsAppPromoText(f: PromoFields): string {
  const lines: string[] = [];
  const emoji = f.introEmoji?.trim() || "🔥";
  const headline = f.introText?.trim() || "PROMOÇÃO";
  lines.push(`${emoji} *${headline}* ${emoji}`, "", `*${f.productName.trim()}*`, "");

  if (f.oldPrice) lines.push(`De: ~${fmtPrice(f.oldPrice, f.currency)}~`);
  lines.push(`Por: *${fmtPrice(f.newPrice, f.currency)}*`);
  if (f.pixPrice) lines.push(`💳 No PIX: *${fmtPrice(f.pixPrice, f.currency)}*`);
  if (f.paymentTerms?.trim()) lines.push(`💰 ${f.paymentTerms.trim()}`);

  if (f.couponCode?.trim()) lines.push("", `🏷️ Cupom: *${f.couponCode.trim()}*`);
  if (f.sizesAvailable?.trim()) lines.push(`📏 Tamanhos disponíveis: ${f.sizesAvailable.trim()}`);

  // The Mercado Livre affiliate link has to be generated by hand in their
  // own tools (there's no API for it) and pasted into affiliateLink — when
  // present it takes over the link line entirely; otherwise the plain
  // product link is used, which still works fine, just without commission.
  const link = f.affiliateLink?.trim() || f.productLink.trim();
  lines.push("", `🔗 ${link}`);

  return lines.join("\n");
}

export type PromoTextToken = { type: "text" | "bold" | "italic" | "strike" | "mono"; value: string };

const TOKEN_RE = /(\*[^*]+\*|_[^_]+_|~[^~]+~|```[^`]+```)/g;

// Splits one line into styled tokens on *bold*/_italic_/~strike~/```mono```.
// Deliberately simple — no nesting, no escaping — since the only producer
// of this text is buildWhatsAppPromoText above, which never emits those
// shapes. Used by WhatsAppPromoPreview and by anything re-rendering a saved
// promo's text (e.g. the list page's "copiar de novo").
export function parseWhatsAppLine(line: string): PromoTextToken[] {
  const tokens: PromoTextToken[] = [];
  const parts = line.split(TOKEN_RE);
  for (const part of parts) {
    if (!part) continue;
    if (part.startsWith("```") && part.endsWith("```") && part.length >= 6) {
      tokens.push({ type: "mono", value: part.slice(3, -3) });
    } else if (part.startsWith("*") && part.endsWith("*") && part.length >= 2) {
      tokens.push({ type: "bold", value: part.slice(1, -1) });
    } else if (part.startsWith("_") && part.endsWith("_") && part.length >= 2) {
      tokens.push({ type: "italic", value: part.slice(1, -1) });
    } else if (part.startsWith("~") && part.endsWith("~") && part.length >= 2) {
      tokens.push({ type: "strike", value: part.slice(1, -1) });
    } else {
      tokens.push({ type: "text", value: part });
    }
  }
  return tokens;
}
